## Numpy arrays & Methods

In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,3,4,5],[6,7,8,9,10]],np.int8)

In [3]:
myarr.shape

(2, 5)

In [4]:
myarr.dtype

dtype('int8')

In [5]:
print(myarr[1][2])

8


In [6]:
Zeroes = np.zeros((3,3))

In [7]:
print(Zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
lsapce = np.linspace(1,5,4)

In [9]:
print(lsapce)

[1.         2.33333333 3.66666667 5.        ]


In [10]:
emp = np.empty((2,2))

In [11]:
print(emp)


[[1.         2.33333333]
 [3.66666667 5.        ]]


In [12]:
new_arr = np.arange(100)

In [13]:
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [14]:
new_arr=new_arr.reshape(2,50)

In [15]:
print(new_arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
  98 99]]


In [16]:
new_arr=new_arr.ravel()

In [18]:
print(new_arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [19]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
x.sum(axis=0)

array([12, 15, 18])

In [22]:
x.sum(axis=1)

array([ 6, 15, 24])

In [23]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [24]:
x.flat

In [25]:
for i  in x.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [26]:
x.ndim 

2

In [28]:
x.nbytes


36

In [29]:
x.size 

9

In [38]:
x.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [36]:
x.argmin()

0

In [33]:
c = np.array([1, 2, 3, 4])
c.argmax()
c.argmin()

0

In [40]:
x.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [50]:
x2 = np.array([[1,2,4],[4,5,7],[9,4,2]])
print(x2)

[[1 2 4]
 [4 5 7]
 [9 4 2]]


In [47]:
# x+x2
x*x2


array([[ 1,  4, 16],
       [16, 25, 49],
       [81, 16,  4]])

In [53]:
np.where(x2>6)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [55]:
import sys

py_ar = [1,2,3,4]
np_ar = np.array(py_ar)

sys.getsizeof(1) * len(py_ar)

112

In [56]:
np_ar.itemsize * np_ar.size

16